<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->delete();

        // Reset id về lại 1
        DB::table('recipes')->truncate();

        // 2. Ta sẽ thêm mới danh mục bằng lệnh create
        DB::table('recipes')->insert([
            [
                'user_id' => 1,
                'title' => 'Gà rán',
                'description' => 'Món gà bắp ram sau khi chiên xong giòn rụm lại trông vô cùng bắt mắt. Khi thưởng thức bạn có thể chấm cùng nước sốt để tăng hương vị món ăn nhé. Nếu bạn là tín đồ của gà rán thì đừng nên bỏ qua món ngon này nhé!',
                'ingredients' => '400 gr thịt ức gà, 60g bột chiên giòn, 180g bột mì, 80g bột bắp, mật ong,tỏi băm,2 quả trứng gà,Bơ, tương ớt hàn quốc, bột ớt hàn quốc, tương cà',
                'instructions' => 'Sơ chế: Thịt gà đem về rửa sạch, thái miếng vừa ăn sau đó bỏ vào 1 chiếc hộp và đổ hết phần bột chiên giòn vào và trộn đều.Bạn lấy 1 chiếc tô sau đó cho 80g bột mì, tiếp tục thêm 40g bột bắp vào sau đó trộn đều 2 loại bột lại với nhau.Đồng thời chuẩn bị 1 chiếc tô khác sau đó đập vào 2 quả trứng gà và cho nốt 80g bột mì và 40g bột bắp còn lại vào và khuấy đều lên, tiếp đến cho thêm 160ml nước lọc và khuấy đến khi bột tan ra là được.\Chiên gà Bạn xiên miếng gà nhúng qua 1 lớp bột ướt sau đó nhúng qua 1 lớp bột khô bỏ gà vào chảo chiên đến khi gà vàng thì vớt gà ra giấy thấm dầu.\Nước sốt gồm: 1 muỗng canh bơ đun cho bơ tan hết, 1 muỗng canh tỏi băm, 2 muỗng canh tương ớt Hàn Quốc, 1 muỗng cà phê ớt bột Hàn Quốc, 1 muỗng canh tương ớt 2 muỗng canh tương cà và khuấy đều sốt lên, tắt bếp và cuối cùng thêm vào 1 muỗng canh mật ong đảo đều rồi cho ra chén.',
                'image' => 'https://cdn.tgdd.vn/Files/2020/08/28/1284763/7-cong-thuc-lam-ga-ran-gion-rum-ngon-hon-ca-ngoai-hang-de-ban-tro-tai-202202231023431295.jpg',
                'id_category' => 4,
                'id_level' => 1,
                'timecook' => '30 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'cánh gà rán',
                'description' => 'Phần gà chiên sau khi hoàn thành khi cắn thử giòn tan trong miệng. Để tăng hương vị bạn đừng quên chấm cùng với tương ớt hoặc tương cà nhé.',
                'ingredients' => '6-7 cánh gà,250g bột chiên giòn, 30g bột bắp,muối , bột nêm, tiêu , bột ớt, tương cà, dầu ăn, giấm',
                'instructions' => 'Sơ chế: Cánh gà mua về làm sạch. Bạn ướp cánh gà với các loại gia vị đã chuẩn bị để 1 tiếng để cánh gà ngấm gia vị.\Chiên gà : Đổ 1 nửa bột bắp và bột chiên giòn vào 1 chiếc bát trộn đều và để khô; phần bột bắp và bột chiên giòn còn lại thì đổ nước vào khuấy cho bột sánh đặc. Tiếp theo bạn lấy cánh gà lăn qua bột ướt rồi lăn qua bột khô.Sau đó cho vào chảo dầu đã đun sôi và chiên cho cánh gà vàng đều các mặt thì lấy ra giấy thấm dầu.',
                'image' => 'https://cdn.tgdd.vn/Files/2020/08/28/1284763/7-cach-lam-ga-ran-sieu-ngon-bo-tui-ngay-de-danh-che-bien-cho-ca-nha-an-nhe-202008311538175468.jpg',
                'id_category' => 4,
                'id_level' => 1,
                'timecook' => '30 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'cánh gà chiên bơ',
                'description' => 'Cánh gà chiên bơ vừa thơm vùa giòn, ăn cùng tương ớt và sốt mayonaise rất ngon, thêm phần thơm ngậy. Ngoài ra, bạn có thể làm đùi gà chiên bơ cũng hấp dẫn không kém nhé!',
                'ingredients' => '450gr cánh gà, 100ml sữa tươi, 3muoongx canh bơ, 3 tép tỏi, 6 muỗng canh bột chiên giòn,tiêu, hạt nêm, đường , bột tỏi, bột ớt',
                'instructions' => 'Sơ chế: Cánh gà rửa sạch và ướp chung với các loại gia vị gồm: ½ muỗng canh bột tỏi, 1 muỗng hạt nêm, ½ muỗng canh tiêu, 1 muỗng canh đường, 1/2 muỗng canh bột ớt sau đó trộn đều và ướp trong thời gian 15 phút.\Chiên gà : Gà sau khi đã ướp được 15 phút thì cho bột chiên giòn vào và thoa đều hết cánh.Bắc chảo lên bếp, đợi chảo nóng thêm dầu ăn vào đun sôi và cho cánh gà vào chiên vàng và gắp ra bỏ vào giấy thấm dầu.Cuối cùng bạn cho bơ vào chảo đun cho bơ chảy, sau đó cho tỏi băm vào đun cho thơm, thêm vào ½ muỗng cà phê ớt xay, tiếp đến cho cánh gà vào vào đảo đều nhớ đun nhỏ lửa để gà không bị cháy và bơ ngấm đều vào cánh gà, sau đó tắt bếp.',
                'image' => 'https://cdn.tgdd.vn/Files/2020/08/28/1284763/7-cach-lam-ga-ran-sieu-ngon-bo-tui-ngay-de-danh-che-bien-cho-ca-nha-an-nhe-202008311540005442.jpg',
                'id_category' => 4,
                'id_level' => 1,
                'timecook' => '30 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Cá Bông lau chua ngọt',
                'description' => 'Cá bông lau chua ngọt là món ăn thơm ngon, hấp dẫn, kết hợp giữa vị chua dịu, ngọt thanh và vị béo mềm tự nhiên của cá bông lau. Đây là món ăn phổ biến trong bữa cơm gia đình, đặc biệt là ở các vùng sông nước miền Tây, nơi cá bông lau được yêu thích nhờ độ béo thơm và thịt mềm đặc trưng.Những miếng cá giòn thơm có màu vàng đẹp mắt, thịt cá mềm thấm đều xốt xào chua ngọt, thêm hành tây và ớt chuông nhiều màu sắc, ngon khỏi bàn, cực bén cơm! Ai mà ngờ Cá Bông Lau lại có thể ngon được đến như thế này! Không thử là tiếc lắm nha! Xắn tay áo vào bếp liền thôi nào.',
                'ingredients' => 'Fillet cá bông lau (còn da) 400g,Ớt chuông xanh 50g (1/4 trái),Ớt chuông đỏ 50g (1/4 trái),Ớt chuông vàng 50g (1/4 trái),Hành tây 25g (1/4 trái),Hành tím băm, Tỏi băm,Đường, Dầu ăn, Tương ớt, Tương cà, hạt nêm, giấm gạo,bột tẩm khô chiên giòn',
                'instructions' => 'Sơ chế: Fillet cá bông lau rửa sạch qua muối pha loãng, để ráo, cắt miếng vuông.Hành tây, ớt chuông xanh, ớt chuông đỏ, ớt chuông vàng rửa sạch cắt vuông cạnh 2cm.Áo cá với 1/2 gói Gia vị nêm sẵn Bột tẩm khô chiên giòn.\Chiên ngập dầu cá với lửa lớn, đến khi da vàng giòn. Vớt ra dĩa để ráo dầu.\Làm xốt: Phi thơm 1m hành tím băm, 1m tỏi băm , cho ớt chuông đỏ, ớt chuông xanh, ớt chuông vàng, hành tây xào đến khi vừa chín tới. Cho hỗn hợp rau ra dĩa. Tiếp tục cho 1M tương ớt, 3M tương cà, 4M nước, 1/2M đường, 1m giấm, 1m Aji heo vào chảo đảo đều đến khi xốt vừa sệt laị. Thêm cá, rau xốc đều cho thấm gia vị. Tắt bếp',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2024/12/Ca-bong-lau-chua-ngot.png.webp',
                'id_category' => 7,
                'id_level' => 1,
                'timecook' => '30 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'cá nục kho top mỡ',
                'description' => 'Cá nục chắc thịt- thơm mùi gừng, thấm đều nước kho đậm đà, cay cay nhẹ, ăn cùng tóp mỡ giòn giòn, beo béo, rất đưa cơm. Vị thân quen nhưng ắt hẳn không phải ai cũng làm đúng được. Có ngay công thức cá nục kho tóp mỡ chuẩn chỉ từ đầu bếp chuyên nghiệp mời bạn thử. Chờ gì nữa? Vào bếp ngay cùng Món Ngon Mỗi Ngày nào!',
                'ingredients' => '300g cá nục,50g mỡ heo,3 trái ớt hiểm,1 củ gừng,1 củ hành tím',
                'instructions' => 'Sơ chế: Cá nục Làm sạch phần mang và bụng sau đó rửa sạch với nước muối loãng. Mỡ heo cắt hạt lựu vừa. Gừng & hành tím cắt lát.\Cho cá nục vào với 1/2m bột ngọt + 1.5M nước mắm + 1M đường cát + 1M tương ớt + 1/4m tiêu xay.\Chuẩn bị nồi rồi cho dầu ăn vào, sau đó cho 50g mỡ heo vào rang cho vừa vàng rồi vớt ra. Tiếp tục dùng dầu đó cho hành tím và gừng phi cho vàng\Cho với cá đã ướp cùng mỡ heo đã ráng và 2 quả ớt hiểm + 1/2M dầu màu điều và 1 chén nước nóng vào đậy nắp kho nhỏ lửa 15 phút',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9qDs8wsj6GFiIB58cRB10FC_9obKLso4swg&s',
                'id_category' => 7,
                'id_level' => 1,
                'timecook' => '35 phút',
                'rating' => 4.5,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Rau xào thập cẩm',
                'description' => 'Rau xào thập cẩm là món ăn ngon dùng cho thực đơn gia đình hàng ngày, có nhiều rau xanh tốt cho sức khỏe và phần nào tránh được bệnh ung thư.',
                'ingredients' => '150g thịt nặc,,70g đậu hà lan,70g nấm rơm,70g bông cải xanh,70g bông cải trắng,1/2 củ cà rốt,1/2 củ hành tây,Tiêu,đường,dầu ăn,hạt nêm,nước tương',
                'instructions' => 'Sơ chế: Thịt nạc dăm cắt lát mỏng, ướp với 1m hành tím băm, 1/2m tiêu, 1/2m đường và 1m hạt nêm, để thấm khoảng 5 phút.Cà rốt tỉa hoa, cắt miếng mỏng. Cà chua, hành tây cắt múi. Nấm rơm ngâm nước muối, rửa sạch, trụng sơ, xẻ hình chữ thập trên đầu nấm. Đậu Hà Lan tước xơ, cắt xéo. Bông cải trắng, bông cải xanh cắt nhỏ. Hành lá, ngò rí cắt khúc 2cm.\Đun sôi nước với 1/2m muối, cho cà rốt và bông cải vào trụng sơ, đến khi nước sôi trở lại thì tắt bếp, vớt rau củ ngâm vào nước lạnh.Đun sôi 3M dầu, phi thơm 1M hành, tỏi băm, xào săn thịt rồi cho cà rốt, bông cải vào xào khoảng 2 phút, cho tiếp nấm rơm vào, nêm 1m hạt nêm, xào đến khi rau củ chín tới, thêm cà chua, hành tây và đậu Hà Lan vào xào nhanh rồi tắt bếp, rắc hành lá và đảo đều.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2015/08/AGF-1745-rau-xao-thap-cam.png.webp',
                'id_category' => 8,
                'id_level' => 1,
                'timecook' => '20 phút',
                'rating' => 4.5,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Rau củ xào đậu hũ xốt mè',
                'description' => 'Rau củ xào đậu hũ ăn với xốt mè vị đậm đà, thơm ngon, rau củ giòn ngọt, vị tươi mát thanh đạm cả nhà cùng giữ chay ngày rằm của lễ Vu Lan nha!',
                'ingredients' => '150g bông cải trắng,100 bí đỏ,1 trái ớt sừng,50g ớt chuông xanh,50g ớt chuông vàng,50g bí ngoài xanh,100g đậu hũ,50g cà chua,1 cây boaro,dầu ăn,đường,mè trắng rang,nước tương,bột ngọt,hạt nêm',
                'instructions' => 'Sơ chế: Boaro cắt lát xéo, để riêng lá và cọng.Pha xốt: 1M Nước tương , 1m hạt nêm Nấm, 1m bột ngọt, 1m đường, 2M nước lọc, 1m mè rang\Chần rau củ: Đậu hũ cắt lát dày 0.5cm, chiên sơ rám mặt.Bông cải trắng tách miếng nhỏ. Bí đỏ cắt lát vừa ăn. Ớt sừng cắt hình thoi. Ớt chuông xanh cắt miếng vừa ăn. Bí ngòi xanh cắt lát. Cà chua bi cắt đôi.Bắt nồi nước đun sôi, chần sơ bông cải trắng rồi vớt ra ngâm nước lạnh, tiếp theo chần sơ bí đỏ rồi vớt ra.\Xào: Phi thơm boaro, cho bông cải, bí đỏ, ớt chuông, bí ngòi vào xào, cho nước xốt vào xóc đều.Cho tiếp lá boaro, cà chua, đậu hũ, ớt sừng vào đảo đều, tắt lửa.',
                'image' => 'https://monngonmoingay.com/wp-content/uploads/2021/08/rau-cu-xao-dau-hu-xot-me-880.webp',
                'id_category' => 8,
                'id_level' => 1,
                'timecook' => '15p',
                'rating' => 4,
                'created_at' => now(),
              ],

              [
                'user_id' => 1,
                'title' => 'khoai tây xào thịt bò phô mai',
                'description' => 'Món Khoai tây xào thịt bò phô mai là sự kết hợp hoàn hảo giữa vị bùi béo của khoai tây, độ mềm ngọt của thịt bò và lớp phô mai kéo sợi thơm lừng.Khoai tây được xào chín tới, vàng nhẹ bên ngoài nhưng vẫn mềm bên trong, thấm gia vị.Thịt bò mềm, không bị dai, được ướp đậm đà, xào vừa chín tới để giữ độ ngọt tự nhiên.Phô mai tan chảy, béo ngậy, bám đều lên khoai tây và thịt bò, tạo thành một lớp sánh mịn hấp dẫn.khi ăn, bạn sẽ cảm nhận được sự hòa quyện giữa vị béo, mặn, ngọt. Bạn có thể ăn kèm bánh mì hoặc cơm nóng đều rất hợp, đảm bảo đưa cơm và cực kỳ gây nghiện!',
                'ingredients' => '400g khoai tây,150g thịt bò xay,60g phô mai mozzarella,dầu ăn,bột ngọt,bơ tươi,1 muỗng dầu ô liu,1 muỗng dầu ăn,50g tương cà,tỏi băm',
                'instructions' => 'Sơ chế: Khoai tây sau khi cắt vuông cờ rửa sạch để ráo, rắc ít muối và trộn đều với 1M dầu ô liu, cho vào nồi chiên không dầu nướng nhiệt độ 160 trong 15p cho khoai chín vàng.\Cho 1M dầu ăn vào chảo, đun nóng rồi phi 1M tỏi vàng thơm. Tiếp theo, cho thịt bò xay vào xào săn cho thịt tơi ra. Cho 50g tương cà và 1/2 chén nước vào xào cho thịt chín mềm. Nêm nếm gia vị gồm: 1m bột ngọt, 1m hạt nêm Heo và 1/4m tiêu. Nước sệt lại, cho hết khoai tây vào xóc chung, cho tiếp 1/2 phô mai và cọng ngò băm vào xóc đều. Cho bơ vào xóc đều rồi tắt lửa.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2025/01/22.-KHOAI-TAY-XAO-THIT-BO-PHO-MAI.png.webp',
                'id_category' => 1,
                'id_level' => 1,
                'timecook' => '25 phút',
                'rating' => 3.5,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'sườn nướng mật ong',
                'description' => 'Món Sườn nướng mật ong hấp dẫn với sự kết hợp hoàn hảo giữa vị ngọt thanh của mật ong và vị đậm đà của sườn nướng. Miếng sườn nướng vàng óng, bóng bẩy được phết một lớp mật ong khi nướng, vừa giòn nhẹ vừa thơm lừng.\Thịt sườn mềm, ngọt, đậm đà: Nhờ quá trình ướp gia vị và nướng, sườn thấm đều, bên ngoài cháy xém nhẹ, bên trong vẫn mềm và mọng nước. Miếng thịt sườn chấm kèm nước xốt phô mai cay đậm đà thơm ngon hết ý.',
                'ingredients' => 'Sườn que 700g,Dầu hào 20g,Nước tương 20g,Mật ong 24g,Bột ngọt 5g,Hành băm 20g,Tỏi băm 20g,Sả băm 10g,Dầu điều 5g,Tiêu 0.5g,sốt mô mai cay',
                'instructions' => 'Sơ chế: Sườn chặt miếng vừa ăn, ướp gia vị khoảng 30 phút.\Đem sườn nướng trong nồi chiên không dầu nhiệt độ 180-190 độ trong 10 phút, sau đó lật lại nướng tiếp khoảng 8 phút.',
                'image' => 'https://www.cet.edu.vn/wp-content/uploads/2018/05/suon-nuong-mat-ong.jpg',
                'id_category' => 2,
                'id_level' => 1,
                'timecook' => '20 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Gỏi bắp bò hoa',
                'description' => 'Món Gỏi bắp bò hoa thanh mát nhưng đầy hương vị, kết hợp hoàn hảo giữa thịt bắp bò mềm ngọt, bắp chuối hột trắng mềm tươi giòn và nước trộn gỏi chua ngọt đậm đà. Đây là món ăn không chỉ ngon mà còn giàu dinh dưỡng, giúp cân bằng khẩu vị trong bữa ăn gia đình.\Bắp bò hoa mềm, ngọt tự nhiên: Bắp bò hoa có phần gân xen kẽ trong thịt, khi luộc hoặc tái chín vừa phải sẽ có độ dai nhẹ, giòn sật và ngọt thơm đặc trưng.\Bắp chuối hột trắng, tươi giòn, thanh mát: Kết hợp với bắp chuối hột tươi giòn, thanh mát, kết hợp với hành, sả thơm ngon.\ước trộn chua ngọt hài hòa: Được pha từ nước mắm ngon, chanh, đường, tỏi ớt, giúp bắp bò và rau củ thấm vị, tạo nên sự kích thích vị giác.\Hạt mè rang bùi thơm: Rắc thêm hạt mè rang vàng giúp món gỏi thêm bùi bùi hấp dẫn.',
                'ingredients' => 'Bắp bò hoa 350g (1 cái),Bắp chuối hột bào, ngâm nước có vắt chanh 100g,Mè rang vàng 20g,Hành tím bào mỏng 1/2 chén,Dừa xiêm 1 trái,Sả bào, sả cây 4 cây sả, 2M sả bào,Ớt băm, sả băm, tỏi băm mỗi thứ 1/2m,Hành tây 1/2 củ, Đường (14g: 1M + 1/2m), nước mắm (8g: 1M),tương ớt (14g: 1M), Rau húng lủi, ớt sừng cắt sợi,Gia vị nêm sẵn Aji-Quick Lẩu Thái,Bột ngọt AJI-NO-MOTO',
                'instructions' => 'Sơ chế: Bắp bò hoa để tủ đông 45 phút, lấy ra cắt lát mỏng. Hành tây cắt khoanh mỏng, rải đều sả bào và hành tây lên đĩa, cho vào tủ mát.Hành tím ướp với một 1/2m đường, để 15 phút.\Pha nước trộn gỏi: Hòa tan 1M đường và 2M nước mắm, 2M nước lọc, 1M tương ớt, cho 1M gia vị nêm sẵn Lẩu Thái, thêm 1/2m ớt băm, 1/2m tỏi băm và 1/2m sả băm vào.\Nước dừa xiêm cho vào nồi, thêm phần còn lại gói gia vị nêm sẵn Lẩu Thái, 4 cây sả đập giập, 1m bột ngọt vào, nấu sôi. Nhúng bắp bò vào, vớt ra để nguội, trộn với hành tím đã ngâm đường, 1/2 nước trộn gỏi vào bò.\Xếp bò lên đĩa bắp chuối, rưới 1/2 nước trộn gỏi còn lại vào, rắc mè rang, ớt sừng, húng lủi lên trên.',
                'image' => 'https://i.ytimg.com/vi/kVcrjQtGm4c/maxresdefault.jpg',
                'id_category' => 1,
                'id_level' => 1,
                'timecook' => '15 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'slad mì udon cá hồi xốt mè rang',
                'description' => 'Salad mì Udon cá hồi xốt mè rang là một món ăn mang hương vị tươi mát, thanh nhẹ nhưng không kém phần đậm đà và bổ dưỡng. Sự kết hợp giữa cá hồi béo ngậy, mì Udon dai mềm và nước xốt mè rang thơm lừng tạo nên một trải nghiệm ẩm thực độc đáo.Salad mì Udon cá hồi xốt mè rang là một món ăn mang hương vị tươi mát, thanh nhẹ nhưng không kém phần đậm đà và bổ dưỡng. Sự kết hợp giữa cá hồi béo ngậy, mì Udon dai mềm và nước xốt mè rang thơm lừng tạo nên một trải nghiệm ẩm thực độc đáo.',
                'ingredients' => 'Mì udon tươi 300g,Xá lách 150g,Cà chua 100g (1 quả),Cá hồi phile 300g,Bắp mỹ 300g (1trái),Hành tây tím 25g, (1/4 củ),Muối, bơ tươi (Anchor), tiêu,Xốt mè rang ',
                'instructions' => 'Sơ chế: Mì udon chần qua nước sôi đến khi sợi mì tách nhau. Vớt ra để ráo, trộn đều với 1M Xốt Mè Rang.Xà lách cắt miếng nhỏ. Cà chua bỏ hạt, cắt hạt lựu.Bắp mỹ: luộc chín, tách lấy hạt. Hành tây cắt lát mỏng chiều ngang, ngâm nước đá cho giòn, để ráo.Cá hồi phi lê cắt lát dày vừa ăn.\Áp chảo cá hồi với bơ lạt cho vừa chín, rắc lên ít muối, tiêu.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2025/01/6.-SALAD-MI-UDON-CA-HOI-XOT-ME-RANG.png.webp',
                'id_category' => 7,
                'id_level' => 1,
                'timecook' => '10 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Bánh mỳ xíu mại',
                'description' => 'ánh mì xíu mại hấp dẫn với sự kết hợp hoàn hảo giữa bánh mì giòn và viên xíu mại mềm ngọt, ngập trong sốt đậm đà. Đây là món ăn sáng phổ biến, dễ ăn và cực kỳ ngon miệng. Món ăn có hương vị đặc biệt từ viên xíu mại được làm từ thịt băm nhuyễn kết hợp với giò sống, trứng và các loại rau củ tạo nên độ ngọt tự nhiên, mềm mịn khi ăn. Nước sốt cà chua đậm đà, chua nhẹ thơm ngọt nước dùng, tất cả kết hợp với bánh mì nóng giòn thơm ngon ăn kèm các loại rau để tăng thêm phần tươi mát, cân bằng hương vị.',
                'ingredients' => 'Thịt nạc dăm xay 150g,Giò sống 30g,Củ sắn 150g,Trứng gà 1 quả,Cà chua chín đỏ 2 trái,Hành lá 2 nhánh,Ngò rí 2 cây,Hành tây băm 3M,Hành tím phi 1M,Bánh mì 4 ổ trung bình,Bột năng 1M + 1m,Đường, muối, tiêu, dầu điều, ketchup, bột năng,Nước tương,Hạt nêm Heo',
                'instructions' => 'Sơ chế:Củ sắn gọt vỏ, cắt sợi, luộc chín rồi vớt ra để nguội, sau đó vắt ráo nước, cắt ngắn.Hành lá cắt nhỏ, đầu hành lá đập dập, băm nhỏ.Cà chua bỏ hạt, băm nhuyễn.\Trộn thịt nạc dăm xay và giò sống với củ sắn, 2m cọng ngò rí băm, 2M hành tây băm, hành phi, đầu hành, hành lá, trứng gà và 1M bột năng. Nêm 1/2m muối, 1m đường, 1m hạt nêm Heo, 1m nước tương và 1/2m tiêu, trộn đều, quết dẻo, rồi cho vào tủ lạnh 15p. Sau đó lấy ra vo viên tròn vừa ăn (cỡ trái tắc) rồi cho vào xửng hấp 10p từ lúc nước sôi.\Làm xốt: Phi thơm đầu hành lá, 1M hành tây băm bằng dầu điều, cho cà chua băm vào xào chín, thêm 2M ketchup, 1 chén nước, nêm 1/2m hạt nêm Heo, 1/2m đường, 1/2m muối, 1m nước tương, nấu nhỏ lửa cho cà chua chín nhừ, cho xíu mại đã hấp vào hỗn hợp xốt nấu trong vòng 5 phút, thêm 1m bột năng hòa nước và 1/2m dầu mè.',
                'image' => 'https://mia.vn/media/uploads/blog-du-lich/banh-mi-xiu-mai-da-lat-doc-dao-am-thuc-xu-ngan-hoa-1634643206.jpg',
                'id_category' => 2,
                'id_level' => 1,
                'timecook' => '25 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Cà tím cuộn thịt chiên',
                'description' => 'Món Cà tím cuộn thịt chiên là một sự kết hợp hài hòa giữa vị béo ngậy của thịt, vị ngọt mềm của cà tím và lớp vỏ giòn rụm hấp dẫn. Khi cắn vào, bạn sẽ cảm nhận được sự giòn tan bên ngoài, sau đó là phần cà tím chín mềm, thấm gia vị, ôm lấy lớp nhân thịt, giò đậm đà bên trong.',
                'ingredients' => 'Cà tím 100g (1 trái to),Nạc dăm xay 150g,Giò sống 50g,Củ năng 4 củ,Trứng gà luộc 1/2 quả,Dưa chuột muối chua 1 quả,Bột năng 5g (1m),Hành lá,Gừng băm (1/2m),Dầu ăn, nước mắm, muối, tiêu, đường, tương ớt,Gia vị nêm sẵn, Bột chiên giòn,Bột ngọt',
                'instructions' => 'Sơ chế:Hành lá đầu hành đập giập băm nhuyễn, phần lá cắt nhỏ, cho vào tô thịt, thêm giò sống, 1/2m gừng băm, củ năng băm, 1/2m bột ngọt , 1/2m hạt nêm Heo, 1/2m đường, 1/4m tiêu, 1/4m muối, 1/2m nước mắm, 1m bột năng, quết đến khi dẻo.Phết nhân thịt lên từng miếng cà tím, cuộn tròn lại, ghim cố định, cho vào tủ đông làm lạnh.Gia vị nêm sẵn Bột chiên giòn pha bột theo hướng dẫn trên bao bì.\Nhúng cà tím cuộn thịt vào hỗn hợp gia vị nêm sẵn  Bột chiên giòn đã pha.Chiên ngập dầu cà tím với lửa vừa, đến khi vàng giòn. Vớt ra để ráo.\Xốt chấm: Trộn đều 1M xốt Mayonnaise Phiên bản ít béo, trứng, dưa chuột muối, 1M tương ớt.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2025/01/21.-CA-TIM-CUON-THIT-CHIEN.png.webp',
                'id_category' => 2,
                'id_level' => 1,
                'timecook' => '35 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Tôm sú kho lá quế',
                'description' => 'Mùa mưa mà được ngồi bên mâm cơm thưởng thức món cơm trắng nóng hổi với tôm kho thì còn gì tuyệt với bằng. Tôm sú thấm vị nước kho, thịt tôm chắc mặn ngọt đậm đà, rất thơm mùi lá quế, nước kho sánh sệt chan vào cơm ăn ngon hết biết.Lá quế không chỉ mang lại mùi thơm dễ chịu mà còn giúp tăng thêm hương vị cho món ăn, làm cho tôm sú trở nên ngon miệng hơn. Món này không chỉ ngon mà còn rất bổ dưỡng, cung cấp nhiều protein và các dưỡng chất cần thiết.',
                'ingredients' => 'Tôm sú (bỏ đầu, vỏ,đuôi) 250g,Lá quế cắt sợi: 30g,Hành tím lột vỏ: 10 củ,Tỏi lột vỏ: 10 tép,Ớt hiểm: 3 trái,Đậu phộng rang: 1M,Bột ngọt 8g (1.5m),Nước mắm 16g (2M),Tiêu 6g (1/2M),Dầu điều 10g (2M),Đường 12g (1M),Lá quế, rau sống,Dầu điều, nước mắm, đường, tiêu,Bột ngọt ',
                'instructions' => 'Sơ chế:Tôm sú xẻ dọc sống lưng lấy chỉ đen. Cắt bỏ phần đuôi nhọn.Lá quế cắt sợi một nửa. Hành tím, tỏi và ớt hiểm đập dập.Ướp tôm với 1.5m bột ngọt , 2M nước mắm, 1/2M tiêu, trộn đều. Thêm hành tỏi, ớt hiểm đập dập, phần lá quế cắt sợi vào trộn đều.Bước 2: Cho 2M dầu điều, 1M đường vào chảo, thắng caramel. Cho tôm vào xào săn, thêm 2M nước và kho đến khi thịt tôm săn lại, thấm đều gia vị, nước kho sệt lại. Rắc lá quế tươi lên mặt. Tắt lửa.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2024/07/tom-su-kho-la-que.jpg.webp',
                'id_category' => 3,
                'id_level' => 1,
                'timecook' => '20 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Hoành thánh tôm xốt vị Thái',
                'description' => 'Hoành thánh tôm xốt vị Thái thơm ngon với lớp vỏ giòn rụm của lá hoành thánh kết hợp với vị ngọt tự nhiên của tôm tươi và nước sốt đậm đà từ hành, tỏi, gừng và cà chua mang hương vị chua cay Thái. Món ăn này không chỉ thơm ngon mà còn mang đến trải nghiệm ẩm thực độc đáo với sự hòa quyện của nhiều tầng hương vị. Cùng Món Ngon Mỗi Ngày vào bếp thực hiện ngay món ăn ngon đơn giản này thôi nào!',
                'ingredients' => 'Lá hoành thánh: 100g,Tôm thẻ bóc vỏ: 100g,Ngò rí: 20g,Hành tây băm: 80g,Hành tím băm: 10g,Tỏi băm: 10g,Gừng băm: 5g,Cà chua băm: 50g,Dầu ăn để chiên: 300g,Gia vị nêm sẵn Lẩu Thái',
                'instructions' => 'Sơ chế:Tôm thẻ dùng dao bản to, đập dẹp, sau đó đặt lên 1 lá hoành thánh, kèm 1 lá ngò rí, rồi kẹp 1 lá hoành thánh khác lên trên.\Đun nóng dầu ăn, lần lượt chiên giòn các lá hoánh thánh, vớt ra để ráo dầu.Pha xốt chấm: Phi thơm hành tím, tỏi, gừng với 1 ít dầu ăn, xào mềm hành tây, cà chua thêm 1/2 chén nước vào nấu sôi, nêm 2m đường, 1M lẩu thái, đun đến khi sốt sánh lại, nếm vị chua ngọt vừa ăn, tắt lửa.',
                'image' => 'https://monngonmoingay.com/wp-content/uploads/2024/12/6.png',
                'id_category' => 3,
                'id_level' => 1,
                'timecook' => '20 phút',
                'rating' => 4,
                'created_at' => now(),
              ],
              [
                'user_id' => 1,
                'title' => 'Salad rong nho xốt mè rang',
                'description' => 'Khi thưởng thức món Salad rong nho xốt mè rang, bạn sẽ cảm nhận được sự hòa quyện của các hương vị rong nho mọng nước, béo béo từ sốt mè rang, và giòn giòn từ rau salad. Màu sắc đẹp mắt hấp dẫn hài hòa từ các loại rau củ, vàng nhạt của xốt và trứng.',
                'ingredients' => 'Xà lách romain 70g,Xà lách lolo 70g,Rong nho tách nước 50g,Trứng gà 3 quả,Cà chua bi 50g,Dưa leo 50g,Bắp cải tím 30g,Xốt mè rang 12g (3M),Xốt mè rang ',
                'instructions' => 'Sơ chế:Xà lách rửa sạch, cắt miếng vừa ăn. Rong nho ngâm nước lạnh 2-3 phút (không quá lâu), vớt ra để ráo.Trứng luộc chín, bóc vỏ, cắt lát.Bắp cải tím bào sợi mỏng. Cà chua bi cắt đôi. Dưa leo rửa sạch, bào sơ vỏ, cắt đôi, sau đó cắt lát mỏng. Lá quế cắt khúc vừa ăn.\Trộn đều các loại xà lách, cà chua, dưa leo, bắp cải tím, lá quế, xếp trứng và rong nho lên trên.',
                'image' => 'https://monngonmoingay.com/wp-content/smush-webp/2024/06/salad-rong-nho-me-rang.jpg.webp',
                'id_category' => 6,
                'id_level' => 1,
                'timecook' => '5 phút',
                'rating' => 4,
                'created_at' => now(),
              ],

              [
                'user_id' => 1,
                'title' => 'Salad thịt hun khói trứng cút',
                'description' => 'Một món ăn phù hợp với tinh thần “Ăn Sạch Sống Khỏe” cho cả nhà – với các loại rau củ giàu chất xơ, thêm thịt ba chỉ hun khói, trứng cút và Xốt Mayonnaise tạo vị thơm béo.',
                'ingredients' => 'Salad iceberg: 1 cây,Salad lolo tím: 1 cây,Củ Radish: 100g,Cà chua bi: 50g,Thịt ba chỉ hun khói: 200g,Ngò tây băm nhỏ,Bánh mì sandwich lạt: 2 lát,Trứng cút luộc: 12 quả,Chanh vàng: 1 trái,muối, dầu olive,Xốt Mayonnaise ',
                'instructions' => 'Sơ chế:Salad rửa sạch cắt khúc 3cm, củ radish cắt lát, cà bi, trứng cút luộc cắt 2. Chanh vàng mài lấy 1M vỏ, vắt lấy nước cốt chanh.Làm crouton: Bánh mì sandwich cắt bỏ rìa xong cắt vuông cạnh 1cm. Đem rang khô trên chảo với lửa nhẹ. Xong xốc với chút dầu olive.\Ba chỉ áp chảo cho săn giòn, cắt ngang 2cm.\Pha hỗn hợp xốt trộn salad:  1M nước cốt chanh, 2M dầu olive, 1M ngò tây băm nhỏ, 4M Xốt Mayonnaise, 1/3m muối.\Trộn salad: trộn các loại salad, củ radish, cà chua bi, vỏ chanh mài, bacon, trứng cút cắt đôi với xốt trộn.',
                'image' => 'https://ajimayo.com.vn/uploads/07-2023/SALADTRUNGRAULUOC_Aji-mayo.jpg',
                'id_category' => 6,
                'id_level' => 1,
                'timecook' => '30 phút',
                'rating' => 4,
                'created_at' => now()
              ],
              [
                'user_id' => 1,
                'title' => 'Vịt om nước tương',
                'description' => 'Thịt vịt om tới độ chín mềm, tươm mỡ, mọng nước ngọt đậm đà. Phần nước om sánh lại quyện với trứng vịt bùi bùi, thơm thơm từ nước tương, cực kì bắt cơm',
                'ingredients' => 'Vịt 1/2 con (1kg)Trứng vịt 4 cái,Nước dừa tươi 1 trái,Hoa hồi 2 tai,Hành tím 5 củ,Gừng băm nhỏ 2M,Tỏi củ 2 củ,Rau quế cắt nhuyễn,Dầu ăn, tiêu trắng hạt, đường thốt nốt, muối, rượu, gừng,Bột ngọt,Nước tương',
                'instructions' => 'Sơ chế:Vịt làm sạch, để ráo, nướng phần da vịt cho vàng rửa lại với nước có rượu và gừng, chặt làm 8 miếng, bỏ bớt phần xương sườn vịt. Khuấy đều 1M đường thốt nốt, 1/2m muối, 1m Bột ngọt và 2M Nước tương, ướp vào vịt, để thấm.Trứng vịt luộc chín, bóc vỏ. Hoa hồi rang thơm. Hành tím và tỏi nướng, bóc vỏ.\Làm nóng dầu ăn, xào thơm gừng băm, tỏi nướng, hành tím nướng, hoa hồi, cho vịt đã ướp vào đảo đều với lửa lớn đến khi thịt vịt săn lại.Thêm 1M tiêu hạt, trứng vịt, 1 chén nước dừa và 1 chén nước lọc vào xăm xắp mặt thịt vịt. Để sôi, vớt bọt hạ nhỏ lửa đậy nắp lại om khoảng 20 phút. Thịt vịt chín mềm, phần nước sánh, nêm 1M Nước tương, tắt lửa.',
                'image' => 'https://monngonmoingay.com/wp-content/uploads/2021/06/vit-om-nuoc-tuong-500.jpg',
                'id_category' => 5,
                'id_level' => 1,
                'timecook' => '20phút',
                'rating' => 4,
                'created_at' => now(),
              ],

              [
                'user_id' => 1,
                'title' => 'Vịt nấu ragu',
                'description' => 'Ragu là món ăn khá quen thuộc với người Việt đặc biệt trong các bữa tiệc, hay những bữa ăn cuối tuần sum họp gia đình. Thường ragu được nấu với bò hoặc gà khá ngon. Hôm nay, Món Ngon Mỗi Ngày xin giới thiệu món ragu được biến tấu với nguyện liệu chính là vịt. Món ăn có vị ngọt thanh, sánhh mượt của nước súp hoà quyện với mùi thơm của vịt và hương thơm của đinh hương và quế chi.',
                'ingredients' => 'Thịt vịt 1/2 con: 1.5 kg,Dừa tươi: 1 trái,Bắp mỹ: 1/2 trái,Sả: 5 cây,Tỏi băm: 1M,Nụ đinh hương: 2 nụ,Quế chi: 1 miếng nhỏ,Cà rốt: 200g,Cà chua tán: 2,5M,Hành tây bi: 150g,Hành tây băm: 1M, ngò,muối, đường, dầu ăn, bột năng, hành tím băm, tỏi băm, hành tây băm,Bột ngọt,Hạt nêm,',
                'instructions' => 'Sơ chế:Thịt vịt áp chảo da (không cần dầu ăn) để tăng mùi vị, chặt miếng to 5cm. Bắp mỹ cắt khoanh.Cho thịt vịt ra tô sau đó cho gia vị 1/2M Hạt nêm, 1m bột ngọt, 1m muối, 2m đường, 1M hành tím băm và 1/2M gừng băm để cho thịt thấm vị 10 phút sau đó sẽ cắt cà rốt hình khối, đập dập sả.\Cho 1M dầu ăn vào nồi sau đó cho hành tây bi vào xóc cho thơm, trút ra rồi.Cho 1M tỏi băm, 1M hành tây băm vào phi thơm cùng với 2.5M cà chua tán, đinh hương và quế vào để tạo màu và hương thơm cho món ăn. Tiếp theo cho hết thịt vịt vào xào cho thơm với lửa lớn cho thịt săn lại và 1.5l cho nước dừa và nước lã vào đun sôi với bọt, sau đó cho sả cây đã đập và hành tay bi vào và nêm thêm 1M hạt nêm vào nấu với lửa vừa 15 phút. Tiếp theo, cho bắp và cà rốt vào nấu thêm 7 phút nữa. Hòa 1M bột năng cùng với nước cho vào để tạo độ sánh cho món ăn.',
                'image' => 'https://monngonmoingay.com/wp-content/uploads/2023/06/vit-nau-ragu-500.png',
                'id_category' => 5,
                'id_level' => 1,
                'timecook' => '40 phút',
                'rating' => 4,
                'created_at' => now()
              ],
        ]);
    }
}
